# Generated by Django 5.2.17 on 2026-10-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0005_tender_prebid_meeting'),
        ('workspaces', '0002_pipeline_invites_api_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('files', models.JSONField(blank=True, default=list)),
                ('rows_seen', models.PositiveIntegerField(default=0)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('license', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'intel_dataset_import',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('trained_at', models.DateTimeField()),
                ('path', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('rows_train', models.PositiveIntegerField(default=0)),
                ('rows_calibration', models.PositiveIntegerField(default=0)),
                ('rows_holdout', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=list)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'intel_model_version',
                'ordering': ['-trained_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_model')],
            },
        ),
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('cpi', 'Cpi'), ('fx_per_usd', 'Fx Per Usd')], max_length=16)),
                ('country', models.CharField(max_length=2)),
                ('year', models.SmallIntegerField()),
                ('value', models.FloatField()),
                ('source', models.CharField(default='worldbank-wdi', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intel_price_index',
                'constraints': [models.UniqueConstraint(fields=('series', 'country', 'year'), name='price_index_key')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=255)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('buyer', models.TextField(blank=True, default='')),
                ('buyer_key', models.TextField(blank=True, db_index=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, choices=[('works', 'Works'), ('goods', 'Goods'), ('services', 'Services'), ('consultancy', 'Consultancy')], default='', max_length=16)),
                ('sector', models.CharField(blank=True, default='', max_length=32)),
                ('method', models.CharField(blank=True, choices=[('open', 'Open'), ('limited', 'Limited'), ('single', 'Single'), ('qcbs', 'Qcbs'), ('reverse_auction', 'Reverse Auction'), ('other', 'Other')], default='', max_length=16)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('award_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('estimated_inr_real', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('award_inr_real', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('num_bidders', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bids', models.JSONField(blank=True, null=True)),
                ('winner', models.TextField(blank=True, default='')),
                ('winner_key', models.TextField(blank=True, db_index=True, default='')),
                ('tender_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('year', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('shared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intel.datasetimport')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.organization')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenders.tender')),
            ],
            options={
                'db_table': 'intel_historical_award',
                'indexes': [models.Index(fields=['country', 'sector', 'year'], name='award_country_sector_year'), models.Index(fields=['state', 'sector', 'year'], name='award_state_sector_year'), models.Index(condition=models.Q(('ratio__isnull', False)), fields=['sector', 'year'], name='award_with_ratio')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='award_source_id'), models.CheckConstraint(condition=models.Q(('ratio__isnull', True), models.Q(('ratio__gte', 0.2), ('ratio__lte', 3.0)), _connector='OR'), name='award_ratio_band')],
            },
        ),
    ]
