# Generated by Django 5.2.17 on 2026-10-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('plan_code', models.CharField(default='free', max_length=32)),
                ('annual_turnover_inr', models.DecimalField(blank=True, decimal_places=2, help_text='average annual turnover of the last 3 financial years', max_digits=18, null=True)),
                ('largest_similar_work_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('years_in_business', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('states', models.JSONField(blank=True, default=list)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.organization')),
            ],
            options={
                'db_table': 'membership',
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='membership_user_org'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='membership_one_active')],
            },
        ),
    ]
