# Generated by Django 5.2.17 on 2026-10-06 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_postgres_search'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='calendar_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='workspaces.organization')),
            ],
            options={
                'db_table': 'api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('preparing', 'Preparing'), ('submitted', 'Submitted'), ('won', 'Won'), ('lost', 'Lost'), ('dropped', 'Dropped')], default='watching', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('bid_amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_tracks', to='workspaces.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenders.tender')),
            ],
            options={
                'db_table': 'bid_track',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], max_length=16)),
                ('nonce_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.organization')),
            ],
            options={
                'db_table': 'workspace_invite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('bid_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workspaces.bidtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bid_reminder_log',
            },
        ),
        migrations.AddConstraint(
            model_name='bidtrack',
            constraint=models.UniqueConstraint(fields=('organization', 'tender'), name='bidtrack_org_tender'),
        ),
        migrations.AddConstraint(
            model_name='bidtrack',
            constraint=models.CheckConstraint(condition=models.Q(('bid_amount_inr__isnull', True), ('bid_amount_inr__gte', 0), _connector='OR'), name='bidtrack_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reminderlog',
            constraint=models.UniqueConstraint(fields=('bid_track', 'user', 'day'), name='reminder_track_user_day'),
        ),
    ]
