# Generated by Django 5.2.17 on 2026-10-07 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0005_tender_prebid_meeting"),
        ("workspaces", "0002_pipeline_invites_api_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bidtrack",
            name="l1_amount_inr",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="bidtrack",
            name="num_bidders",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bidtrack",
            name="our_rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bidtrack",
            name="winner_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="contribute_outcomes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="bidtrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("l1_amount_inr__isnull", True), ("l1_amount_inr__gte", 0), _connector="OR"
                ),
                name="bidtrack_l1_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bidtrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("num_bidders__isnull", True),
                    models.Q(("num_bidders__gte", 1), ("num_bidders__lte", 500)),
                    _connector="OR",
                ),
                name="bidtrack_num_bidders_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="bidtrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("our_rank__isnull", True),
                    models.Q(
                        ("our_rank__gte", 1),
                        models.Q(
                            ("num_bidders__isnull", True),
                            ("our_rank__lte", models.F("num_bidders")),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="bidtrack_rank_within_bidders",
            ),
        ),
    ]
