# Generated by Django 5.2.17 on 2026-10-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=48)),
                ('period', models.CharField(max_length=7)),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='workspaces.organization')),
            ],
            options={
                'db_table': 'billing_usage',
                'constraints': [models.UniqueConstraint(fields=('organization', 'key', 'period'), name='usage_org_key_period')],
            },
        ),
    ]
