# Generated by Django 5.2.17 on 2026-10-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'billing_webhook_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=32)),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('pending', 'Pending'), ('halted', 'Halted'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='created', max_length=16)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('fake', 'Fake'), ('manual', 'Manual')], max_length=16)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspaces.organization')),
            ],
            options={
                'db_table': 'billing_subscription',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
