# Generated by Django 5.2.17 on 2026-10-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('mode', models.CharField(default='incremental', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('mismatch', 'Mismatch'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='running', max_length=16)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('pages', models.IntegerField(default=0)),
                ('new', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('quarantined', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('expected', models.IntegerField(blank=True, null=True)),
                ('listed', models.IntegerField(blank=True, null=True)),
                ('reconciliation', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crawl_run',
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('error', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('last_tried', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dead_letter',
            },
        ),
        migrations.CreateModel(
            name='RawPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('index', 'Index'), ('listing', 'Listing'), ('detail', 'Detail')], max_length=16)),
                ('url', models.TextField()),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField()),
                ('body_hash', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('source_tender_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('crawl_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.crawlrun')),
            ],
            options={
                'db_table': 'raw_page',
            },
        ),
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('errors', models.JSONField()),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.rawpage')),
            ],
            options={
                'db_table': 'quarantine',
            },
        ),
        migrations.CreateModel(
            name='CrawlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tender_id', models.CharField(max_length=128)),
                ('organisation', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('new', 'New'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped', 'Skipped'), ('quarantined', 'Quarantined'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crawl_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ingest.crawlrun')),
                ('raw_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.rawpage')),
            ],
            options={
                'db_table': 'crawl_item',
            },
        ),
        migrations.AddIndex(
            model_name='rawpage',
            index=models.Index(fields=['kind', 'fetched_at'], name='raw_page_kind_8d5eb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawlitem',
            constraint=models.UniqueConstraint(fields=('crawl_run', 'source_tender_id'), name='uniq_crawl_item_per_run'),
        ),
    ]
