# Generated by Django 5.2.17 on 2026-10-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.TextField()),
                ('norm_key', models.TextField(db_index=True)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'buyer_entity',
            },
        ),
        migrations.CreateModel(
            name='BuyerAlias',
            fields=[
                ('alias', models.TextField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('method', models.CharField(choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy'), ('manual', 'Manual'), ('seed', 'Seed')], max_length=16)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='tenders.buyerentity')),
            ],
            options={
                'db_table': 'buyer_alias',
            },
        ),
        migrations.CreateModel(
            name='BuyerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField()),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenders.buyerentity')),
            ],
            options={
                'db_table': 'buyer_review',
                'constraints': [models.UniqueConstraint(fields=('alias', 'candidate'), name='uniq_review_pair')],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_tender_id', models.CharField(max_length=128)),
                ('ref_no', models.TextField(blank=True, default='')),
                ('title', models.TextField()),
                ('buyer_raw', models.TextField()),
                ('org_chain', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('product_category', models.CharField(blank=True, default='', max_length=128)),
                ('tender_type', models.CharField(blank=True, default='', max_length=64)),
                ('value_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('emd_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fee_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('published_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, default='')),
                ('pincode', models.CharField(blank=True, default='', max_length=6)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('url', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('buyer_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.buyerentity')),
                ('raw_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingest.rawpage')),
            ],
            options={
                'db_table': 'tender',
                'indexes': [models.Index(fields=['closes_at'], name='tender_closes__3511b9_idx'), models.Index(fields=['state'], name='tender_state_c371f2_idx'), models.Index(fields=['category'], name='tender_categor_469d65_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_tender_id'), name='tender_source_source_tender_id_uniq'), models.CheckConstraint(condition=models.Q(('closes_at__gte', models.F('published_at'))), name='tender_closes_after_published'), models.CheckConstraint(condition=models.Q(('value_inr__isnull', True), ('value_inr__gte', 0), _connector='OR'), name='tender_value_non_negative')],
            },
        ),
    ]
