# Generated by Django 5.2.17 on 2026-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='sector',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
