# Generated by Django 5.2.17 on 2026-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """Tender.prebid_meeting (nullable): the portal's "Pre Bid Meeting Date". Additive; rows
    loaded before it get the date on their next crawl or `manage.py backfill`."""

    dependencies = [
        ("tenders", "0004_postgres_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="prebid_meeting",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
