# Generated by Django 5.2.17 on 2026-10-01 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug'), ('data', 'Wrong or missing data'), ('idea', 'Idea or request'), ('private_waitlist', 'Private tenders waitlist'), ('other', 'Other')], max_length=24)),
                ('message', models.TextField(blank=True, default='', max_length=4000)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('page', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('done', 'Done')], default='new', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
