# Generated by Django 5.2.17 on 2026-10-06 11:46

import copilot.models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


# Full-text side of hybrid retrieval: heading weighted above body text, english stemming
# ("deposits" finds "deposit"). STORED and GENERATED like tender.search_vector, so bulk
# inserts need no extra step; not a model field (copilot.models.Chunk).
CHUNK_SEARCH_VECTOR = """
    setweight(to_tsvector('english'::regconfig, coalesce(heading, '')), 'A')
    || setweight(to_tsvector('english'::regconfig, coalesce(text, '')), 'B')
"""


class Migration(migrations.Migration):
    """Copilot documents and chunks. Depends on tenders 0004, which creates the pgvector
    extension."""


    initial = True

    dependencies = [
        ('tenders', '0004_postgres_search'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=copilot.models.upload_path)),
                ('sha256', models.CharField(max_length=64)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('ocr_pages', models.PositiveIntegerField(default=0)),
                ('bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('page_texts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.organization')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_documents', to='tenders.tender')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.PositiveIntegerField()),
                ('page_from', models.PositiveIntegerField()),
                ('page_to', models.PositiveIntegerField()),
                ('heading', models.TextField(blank=True, default='')),
                ('text', models.TextField()),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='copilot.document')),
            ],
            options={
                'ordering': ['document', 'ord'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'tender'], name='copilot_doc_org_tender'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('organization', 'sha256'), name='copilot_doc_org_sha'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='copilot_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'ord'), name='copilot_chunk_doc_ord'),
        ),
        migrations.RunSQL(
            f"ALTER TABLE copilot_chunk ADD COLUMN search_vector tsvector "
            f"GENERATED ALWAYS AS ({CHUNK_SEARCH_VECTOR}) STORED;"
            "CREATE INDEX copilot_chunk_search_vector ON copilot_chunk USING gin (search_vector);",
            "DROP INDEX IF EXISTS copilot_chunk_search_vector;"
            "ALTER TABLE copilot_chunk DROP COLUMN IF EXISTS search_vector;",
        ),
    ]
