// Writes the Caddyfile lines that set the app's Content-Security-Policy (imported by
// deploy/caddy/Caddyfile). Run at image build time on the built index.html:
//
//   node csp.mjs dist/index.html > csp.caddy
//
// Inline <script>s (the theme bootstrap that avoids a white flash) are allowed by their
// sha256 hash, recomputed on every build, instead of 'unsafe-inline'.
// External origins, all of them loaded by the frontend on purpose (grep frontend/src):
//   Google Fonts (index.html), Google sign-in (lib/auth.tsx), Razorpay Checkout
//   (lib/billing.ts), Google profile pictures (Layout.tsx).
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const html = readFileSync(process.argv[2] ?? "dist/index.html", "utf8");
const hashes = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)]
  .map((m) => m[1])
  .filter((body) => body.trim())
  .map((body) => `'sha256-${createHash("sha256").update(body).digest("base64")}'`);

const policy = {
  "default-src": ["'self'"],
  "script-src": ["'self'", ...hashes, "https://accounts.google.com/gsi/client", "https://checkout.razorpay.com"],
  "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://accounts.google.com/gsi/style"],
  "font-src": ["'self'", "data:", "https://fonts.gstatic.com"],
  "img-src": ["'self'", "data:", "blob:", "https://*.googleusercontent.com", "https://*.razorpay.com"],
  "connect-src": ["'self'", "https://accounts.google.com/gsi/", "https://*.razorpay.com"],
  "frame-src": ["https://accounts.google.com/gsi/", "https://api.razorpay.com", "https://checkout.razorpay.com"],
  "worker-src": ["'self'"],
  "manifest-src": ["'self'"],
  "object-src": ["'none'"],
  "base-uri": ["'self'"],
  "form-action": ["'self'"],
  "frame-ancestors": ["'self'"],
};
const value = Object.entries(policy)
  .map(([k, v]) => `${k} ${v.join(" ")}`)
  .join("; ");

// @app is defined in the Caddyfile: every response except the Swagger page, which has its own.
console.log(`# Generated by deploy/caddy/csp.mjs from index.html; do not edit.`);
console.log(`header @app Content-Security-Policy "${value}"`);
